version: '3.8'

services:

  mariadb:
    image: mariadb:10.7
    container_name: fusionsuite_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
  
  adminer:
    image: adminer:4.8.1
    restart: always
    environment: 
      ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - 8080:8080
    depends_on:
      - "mariadb"