version: '3.8'

services:
    frontend:
      build:
        context: .
        dockerfile: ./frontend/dockerfile
      ports:
        - "8080:80"
    
    backend:
      build:
        context: .
        dockerfile: ./backend/dockerfile
      ports:
        - "80:80"
        - "3306:3306"
