version: '3.8'

services:
    frontend:
      build:
        context: .
        dockerfile: ./frontend/dockerfile
    
    backend:
      build:
        context: .
        dockerfile: ./backend/dockerfile
