FROM mariadb:10.7

ENV MYSQL_ROOT_PASSWORD root123
ENV MYSQL_DATABASE fusionsuite_db
ENV MYSQL_USER fusionsuite_user
ENV MYSQL_PASSWORD StrongDBPassword

# Expose the default port
EXPOSE 3306

RUN apt-get update -y && \
apt-get upgrade -y